# Generated by Erlang.mk. Edit at your own risk!

ERTS_INCLUDE_DIR ?= /home/xentime/erlang/R2330/erts-11.2/include/
ERL_INTERFACE_INCLUDE_DIR ?= /home/xentime/erlang/R2330/lib/erl_interface-4.0.2/include
ERL_INTERFACE_LIB_DIR ?= /home/xentime/erlang/R2330/lib/erl_interface-4.0.2/lib
ERTS_DIR ?= /home/xentime/erlang/R2330/lib/erts-11.2
